

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  namespace: bggns
  labels:
    app: bgg
    name: bggapp-deploy

spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  replicas: 3
  selector:
    matchLabels:
      app: bgg
      name: bgg-pod
      

  template:
    metadata:
      name: bggapp-pod
      namespace: bggns
      labels:
        app: bgg
        name: bgg-pod
        

    spec:
      containers:
      - name: bggapp-container
        image: stackupiss/bgg-backend:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: bggapp-config
        - secretRef:
            name: bggapp-secret
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          timeoutSeconds: 5
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          timeoutSeconds: 5
          failureThreshold: 1
          successThreshold: 1
        




---

apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: bggns
  labels:
    app: bgg
    name: bggapp-svc
        
spec:
  type: ClusterIP
  selector:
    app: bgg
    name: bgg-pod
    
  ports:
  - port: 8000
    targetPort: 3000