
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  namespace: bggns
  labels:
    app: bgg
    name: bggdb-deploy

spec:
  replicas: 1
  selector:
    matchLabels: 
      app: bgg
      name: bggdb-pod
      # commit: abc123
  template:
    metadata:
      name: bggpod
      namespace: bggns
      labels: # labels are important here
        app: bgg
        name: bggdb-pod
        # commit: abc123

    spec:
      containers:
      - name: bggdb-container
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort : 3306
        # env:
        # - name: INSTANCE_NAME
        #   value: database
        # - name: INSTANCE_HASH
        #   value: abc123

--- 

apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns
  labels:
    app: bgg
    name: bggdb-svc

spec:
  type: ClusterIP
  selector:
    app: bgg
    name: bggdb-pod
    # commit: abc123
  ports:
  - port: 3306
    targetPort: 3306
    

        